### ISSUE TITLE
Clicking on links in pinned notes causes a note to revert to default setting

### ISSUE THREAD

**Issue by autonomygaps** [bwydoogh/obsidian-force-view-mode-of-note#11] opened 2021-09-01 05:53 UTC
Here's my situation:  
- I have a note set to default to Edit mode, with `obsidianUIMode: source`;
- I manually change the view mode of the note to preview and "pin" the note so that I can open several links from that note;
- After I click the link, and a new page opens, but the view mode of the pinned note reverts to Edit mode.

It looks like following a link generates a refresh of the note, and the plugin treats a refresh as if it the note were being opened the first time.

Sadly, this makes the plugin unusable for me.

**Comment by bwydoogh** [comment] 2021-09-01 08:13
Duplicate of https://github.com/bwydoogh/obsidian-force-view-mode-of-note/issues/4 - closing this issue. 

I will add a setting so you can decide whether you want to always return to the default Obsidian view mode (or not).

**Closed by bwydoogh** 2021-09-01 08:13 UTC

**Comment by autonomygaps** [comment] 2021-09-01 14:35
Terrific!  I look forward to it!
