### ISSUE TITLE
Obsidian not respecting the preview/source UI properties

### ISSUE THREAD

**Issue by stutopp** [bwydoogh/obsidian-force-view-mode-of-note#38] opened 2024-02-26 07:32 UTC
I can't get any of my notes to use the preview/source and live/source properties. No idea what's going on.

My settings:
- Ignore opened files.
- Ignore force view when not in frontmatter.
- Debounce: 1000 (tried 0, 300, 2500)
- no folders/files configured.

It doesn't matter if I open from another file, the quick switcher, the file explorer--it always goes back to source view mode and live editing mode. Any advice is appreciated.

**Comment by bwydoogh** [comment] 2024-03-01 07:47
I cannot reproduce this issue, nor have I received similar reports.

Have you checked whether there are error messages appearing when opening the developer tools ("View" > "Toggle Developer Tools")? Perhaps another plugin is causing issues.

Closing for now. Please let me know if you have any more information that could be related to this plugin.

**Closed as completed by bwydoogh** 2024-03-01 07:47 UTC

**Comment by stutopp** [comment] 2024-03-06 03:38
Looks like it's working because I complained. TY!
