### ISSUE TITLE
Folding is interfered with

### ISSUE THREAD

**Issue by menagerie198** [bwydoogh/obsidian-force-view-mode-of-note#9] opened 2021-08-28 10:11 UTC
Hi, I think this plugin is affecting the fold function in core Obsidian (0.12.14). Is that likely? I have been experiencing 'unfolding' when moving between different files. Apologies for being so vague - I cannot find a consistent pattern to the behaviour.

**Comment by bwydoogh** [comment] 2021-08-28 11:57
Should not be the case. I will have a look; I am using folding as well without noticing anything strange yet.

**Comment by bwydoogh** [comment] 2021-08-29 17:46
I cannot reproduce this issue; closing this issue. This plug-in does not touch anything related to folding / unfolding _(FYI: using a pinned "dashboard" note myself; some sections (marked by headings) are most of the time folded)_.

**Closed by bwydoogh** 2021-08-29 17:46 UTC
